DEFAULT_BASE_URL = "https://api.nansen.ai/api/v1"
POINTS_BASE_URL = "https://app.nansen.ai"
DEFAULT_TIMEOUT = 60.0
DEFAULT_MAX_RETRIES = 2
INITIAL_RETRY_DELAY = 0.5
MAX_RETRY_DELAY = 8.0
API_KEY_ENV_VAR = "NANSEN_API_KEY"
